{
 "title": "Dashboard Pacientes",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "PatientID",
    "label": "Patient ID",
    "query": "SHOW TAG VALUES FROM \"blood-oxygen\" WITH key=\"patient-id\""
   }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "\n<div style=\"padding:16px;background-color:white;margin-top:16px;display:block;margin-left:auto;margin-right:auto;width:100%;height:100%;\">\n<img height=\"126px\" style=\"padding-left:14%;display:inline;\" src=\"https://www.estudiaradistancia.es/logos/original/logo-universidad-de-extremadura.png\" alt=\"Logo unex\" />\n<h1 style=\"display:inline;color:#000000;text-align:center;margin-top:16px;\">Servidor de visualización de datos de sensores</h1>\n</div>\n"
   },
   "targets": [
    {}
   ]
  },
  { "title": "Oxígeno en sangre", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 } },
  {
   "title": "Oxigeno en sangre SpO2 - Paciente: ${PatientID}",
   "type": "graph",
   "gridPos": { "h": 8, "w": 9, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "blood-oxygen",
     "query": "SELECT \"value\" FROM \"blood-oxygen\"  WHERE \"patient-id\" = '${PatientID}'",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Oxígeno en sangre actual - Paciente: ${PatientID}",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 6, "x": 9, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "SpO2" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT \"value\" FROM \"blood-oxygen\"  WHERE \"patient-id\" = '${PatientID}'",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Alertas por nivel bajo de oxígeno - Paciente: ${PatientID}",
   "type": "table",
   "gridPos": { "h": 8, "w": 9, "x": 15, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "SpO2" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT \"meassured-value\" as \"Valor de la alarma\" FROM \"alarm\"  WHERE \"patient-id\" = '${PatientID}'  AND \"type\" = 'blood-oxygen' ORDER BY DESC",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  { "title": "Ritmo cardiaco", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 } },
  {
   "title": "Pulsaciones por minuto - Paciente: ${PatientID}",
   "type": "graph",
   "gridPos": { "h": 8, "w": 9, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "ppm" } },
   "yaxes": [
    { "format": "ppm" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "blood-oxygen",
     "query": "SELECT \"value\" FROM \"heartbeat\"  WHERE \"patient-id\" = '${PatientID}'",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Pulsaciones por minuto actual - Paciente: ${PatientID}",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 6, "x": 9, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "ppm" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT \"value\" FROM \"heartbeat\"  WHERE \"patient-id\" = '${PatientID}'",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Alertas por pulso peligroso - Paciente: ${PatientID}",
   "type": "table",
   "gridPos": { "h": 8, "w": 9, "x": 15, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "PPM" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT \"meassured-value\" as \"Valor de la alarma\" FROM \"alarm\"  WHERE \"patient-id\" = '${PatientID}'  AND \"type\" = 'heartbeat' ORDER BY DESC",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  { "title": "Temperatura", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 } },
  {
   "title": "Temperatura - Paciente: ${PatientID}",
   "type": "graph",
   "gridPos": { "h": 8, "w": 9, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "blood-oxygen",
     "query": "SELECT \"value\" FROM \"temperature\"  WHERE \"patient-id\" = '${PatientID}'",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Temperatura actual - Paciente: ${PatientID}",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 6, "x": 9, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "SpO2" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT \"value\" FROM \"temperature\"  WHERE \"patient-id\" = '${PatientID}'",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Alertas por temperatura peligrosa - Paciente: ${PatientID}",
   "type": "table",
   "gridPos": { "h": 8, "w": 9, "x": 15, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT \"meassured-value\" as \"Valor de la alarma\" FROM \"alarm\"  WHERE \"patient-id\" = '${PatientID}'  AND \"type\" = 'temperature' ORDER BY DESC",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  }
 ]
}