apiVersion: v1
kind: Secret
metadata:
  name: influxdb-auth
  namespace: tfg-edge
type: Opaque
stringData:
  influxdb-database: "clinicdata"
  influxdb-username: "test-user"
  influxdb-password: "test-password"